### ISSUE TITLE
Linker error on Ubuntu 20.04 

### ISSUE THREAD

**Issue by fabianvanrissenbeck** [dmatlack/chip8#3]
When compiling by running ```make``` ld runs into the following issue:
```
/usr/bin/ld: /tmp/ccdh3TJg.o: in function `paint_cell':
play.c:(.text+0x226): undefined reference to `paint_pixel'
collect2: error: ld returned 1 exit status
make: *** [Makefile:9: play] Error 1
```
This issue is caused by inlining the function paint_pixel() in play.c.
Removing the inline keywords solves this issue.

**Comment by 0xtrzy** [comment]
/usr/bin/ld: /tmp/ccfBTQG6.o: in function `paint_cell':
play.c:(.text+0x1e9): undefined reference to `paint_pixel'
collect2: error: ld returned 1 exit status

on fedora
